name: "core"
description: "A new Flutter package project."
version: "0.0.1"
homepage: null
environment:
  sdk: "^3.9.0"
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: "flutter"
  flutter_localizations:
    sdk: "flutter"
  dartz: "^0.10.1"
  dio: "^5.4.0"
  flutter_bloc: "^8.1.3"
  get_it: "^7.6.7"
  go_router: "^13.2.0"
  intl: "any"
  google_fonts: "^6.1.0"
  flutter_animate: "^4.5.0"
  shared_preferences: "^2.2.2"
  image_picker: "^1.0.7"
  url_launcher: ^6.3.2
dev_dependencies:
  flutter_test:
    sdk: "flutter"
  flutter_lints: "^5.0.0"
flutter: null
